'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Grocery_List.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21593536b42ac07bba99272748ac0f7c_f69aca4a_c60b_4105_a6e6_78bacdbe52d3_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21593536b42ac07bba99272748ac0f7c_f69aca4a-c60b-4105-a6e6-78bacdbe52d3_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2GOExpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2GOExpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4214d07a86222f3315561369433c6f37_7def350d_3cbd_4724_9f6d_3dc090068291_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4214d07a86222f3315561369433c6f37_7def350d-3cbd-4724-9f6d-3dc090068291_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _93634() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93634", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AjinomotoMSG16oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjinomotoMSG16oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AjishimaRiceSeasoning_SalmonFurikake1_7oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjishimaRiceSeasoning-SalmonFurikake1.7oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ArgentinaLuncheonMeat12ozFRONT_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArgentinaLuncheonMeat12ozFRONT_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C2GreenTea_Apple16_9ozfront_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C2GreenTea-Apple16.9ozfront_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalbeeFruitGranolaCereal_ChocolateCrunch_BananaFlavor15oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalbeeFruitGranolaCereal-ChocolateCrunch_BananaFlavor15oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalbeeKettleChips_LightlySalted5_29oz_150g__front_1024x1024_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalbeeKettleChips-LightlySalted5.29oz_150g__front_1024x1024@2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Century_Tuna_Flakes_in_Oil_FRONT_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Century-Tuna-Flakes-in-Oil_FRONT_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChikyuUmaJapaneseStyleSlicedSushiGinger_White_12oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChikyuUmaJapaneseStyleSlicedSushiGinger_White_12oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d_76185d6a_6acc_47f0_80f0_276454229fbc_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d_76185d6a-6acc-47f0-80f0-276454229fbc_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D_PlusBakedWheatCake_CoffeeFlavor2_82oz_80g__front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D-PlusBakedWheatCake-CoffeeFlavor2.82oz_80g__front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Datu_Puti_Pinoy_Spiced_Coconut__Tuba__Vinegar_Front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Datu-Puti-Pinoy-Spiced-Coconut-_Tuba_-Vinegar_Front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DelMonte100_PineappleJuice33_8oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DelMonte100_PineappleJuice33.8oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DHL_Express() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DHL_Express", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DonaMariaJasponicaWhiteRice70_54oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DonaMariaJasponicaWhiteRice70.54oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fibisco_Choco_Crunchies_cd795079_047f_4923_a2a4_2e933e388bcb_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fibisco_Choco_Crunchies_cd795079-047f-4923-a2a4-2e933e388bcb_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GenkiForestSugar_FreeSparklingWater_WhitePeachFlavor16_23oz_480ml_____16_23oz_480ml__front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GenkiForestSugar-FreeSparklingWater-WhitePeachFlavor16.23oz_480ml_-_-_16.23oz_480"& _ 
                        "ml__front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_add_shopping_cart_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-add-shopping-cart-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_exit_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-exit-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_help_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-help-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_help_901() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-help-901", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_help_902() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-help-902", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_more_info_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-more-info-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_truck_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-truck-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ITOENMatchaLoveEnergy_Soothe8_28oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ITOENMatchaLoveEnergy_Soothe8.28oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property J_BasketCreamyMisoDressing12oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J-BasketCreamyMisoDressing12oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property J_BasketSushiWasabiPowder0_88oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J-BasketSushiWasabiPowder0.88oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property J_T_Express() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("J_T_Express", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JacknJill_Cheese_PotatoCrisps_9b2ad34e_8d09_492f_9149_e8e5b12bcacc_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JacknJill_Cheese_PotatoCrisps_9b2ad34e-8d09-492f-9149-e8e5b12bcacc_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JacknJill_Chicharrow_Ni_mang_juan_0bcb323c_a18d_48fb_bdd7_ad847d72689c_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JacknJill_Chicharrow_Ni_mang_juan_0bcb323c-a18d-48fb-bdd7-ad847d72689c_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JacknJill_Nacho_Cheese_Corn_Chips_bb0d0af5_2068_4166_bbe8_bbbfc8f928de_1024x1024_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JacknJill_Nacho_Cheese_Corn_Chips_bb0d0af5-2068-4166-bbe8-bbbfc8f928de_1024x1024@"& _ 
                        "2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JRS_Express() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JRS_Express", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KikkomanNoodleKitwithSauce_BlackPepperFlavor4_8oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KikkomanNoodleKitwithSauce-BlackPepperFlavor4.8oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KiminoRingoSparklingJuice8_45oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KiminoRingoSparklingJuice8.45oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KiminoYuzuSparklingWater8_45oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KiminoYuzuSparklingWater8.45oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KnorrTamarindWithGabiPhilippines0_78oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KnorrTamarindWithGabiPhilippines0.78oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kopiko_3_In_1_Coffee_Brown___Creamy__30Packs__Front_0b1c4458_2a4f_4d14_9a4e_6192932844c8_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kopiko-3-In-1-Coffee-Brown-_-Creamy-_30Packs__Front_0b1c4458-2a4f-4d14-9a4e-61929"& _ 
                        "32844c8_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KSK_BoyBawangCornick_Galic_12fd19d9_e5a1_4997_b3c9_eb316782de48_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KSK_BoyBawangCornick_Galic_12fd19d9-e5a1-4997-b3c9-eb316782de48_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ladys_Choice_Sandwich_Spread_15oz_FRONT_761345ae_c8ed_4f37_b102_154c2a4ee06b_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ladys-Choice-Sandwich-Spread-15oz_FRONT_761345ae-c8ed-4f37-b102-154c2a4ee06b_540x"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LBC_Express() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LBC_Express", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LotteCrunkyCrunchChocolate1_58oz_45g__front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LotteCrunkyCrunchChocolate1.58oz_45g__front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuciaAssortedPastillas5_25oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuciaAssortedPastillas5.25oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lucky_Me_Supreme_Bulalo_FRONT_8c2e7c74_8192_4c9a_87e8_461073421d73_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lucky-Me-Supreme-Bulalo_FRONT_8c2e7c74-8192-4c9a-87e8-461073421d73_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuckyMe_Beef_Mami_47dd6d92_fe84_4028_a10b_c86296b6fd49_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuckyMe_Beef_Mami_47dd6d92-fe84-4028-a10b-c86296b6fd49_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuckyMe_Citrus_21de2b73_5169_4121_882e_cc15af6cb7e2_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuckyMe_Citrus_21de2b73-5169-4121-882e-cc15af6cb7e2_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuckyMePancitCantonChilimansi2_29oz_Front_fa5b3c02_7631_465a_bcf8_3d9f8510513e_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuckyMePancitCantonChilimansi2.29oz_Front_fa5b3c02-7631-465a-bcf8-3d9f8510513e_54"& _ 
                        "0x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LuckyMePancitCantonChilimansi21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LuckyMePancitCantonChilimansi21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maeda_enMatchaGreenTeaPowder1oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maeda-enMatchaGreenTeaPowder1oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MagnoliaStarMargarineClassique8_82oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MagnoliaStarMargarineClassique8.82oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MamaSita_sChamporadoRiceandCacaoPorridgeKit9_52oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MamaSita_sChamporadoRiceandCacaoPorridgeKit9.52oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mang_Tomas_All_Purpose_Sauce_19_4oz_Front_20a0c115_2139_432d_9736_5a8b0491f9eb_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mang_Tomas_All_Purpose_Sauce_19.4oz_Front_20a0c115-2139-432d-9736-5a8b0491f9eb_54"& _ 
                        "0x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaruichiIsoyakiHotategai_SeasonedScallop1_69oz_48g__front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaruichiIsoyakiHotategai-SeasonedScallop1.69oz_48g__front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MarukanRiceVinegar_SweetandTangyFlavor12oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarukanRiceVinegar-SweetandTangyFlavor12oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property McCormickVanillaFlavorExtract0_68oz_20ml__front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("McCormickVanillaFlavorExtract0.68oz_20ml__front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meiji_af2ff121_8aeb_4997_9a5e_b79cf4267103_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meiji_af2ff121-8aeb-4997-9a5e-b79cf4267103_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MyojoIppei_ChanYomise_no_YakisobaOrientalFlavorwithMayonnaise4_58oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MyojoIppei-ChanYomise-no-YakisobaOrientalFlavorwithMayonnaise4.58oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NinjaVan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NinjaVan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NishikiPremiumGradeRice32oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NishikiPremiumGradeRice32oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NissinDemaeRamenNoodle_SpicyFlavor3_5oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NissinDemaeRamenNoodle-SpicyFlavor3.5oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Royal_Tru_Orange_Can_FRONT_f0825594_b9c4_4c1e_b7bf_8fd64e390f81_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal-Tru-Orange-Can_FRONT_f0825594-b9c4-4c1e-b7bf-8fd64e390f81_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SB_GoldenCurry_Sauce_with_Vegetables_Hot_Box_9d6afb44_5b66_4c62_9179_05b9c3e44a3b_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SB_GoldenCurry_Sauce_with_Vegetables_Hot_Box_9d6afb44-5b66-4c62-9179-05b9c3e44a3b"& _ 
                        "_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SB_Wasabi_88c33bc9_8512_4e03_b5a1_40ee78b6ddbb_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SB_Wasabi_88c33bc9-8512-4e03-b5a1-40ee78b6ddbb_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SB_Wasabi_Sauce_04715382_e2c7_4e98_a9f7_da1374a3813a_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SB_Wasabi_Sauce_04715382-e2c7-4e98-a9f7-da1374a3813a_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shirakiku_Japanese_Bread_Crumbs_20f841b7_5bdf_4179_b12f_db923d101fd7_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shirakiku_Japanese_Bread_Crumbs_20f841b7-5bdf-4179-b12f-db923d101fd7_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ShirakikuRoastedBlackSesameSeed8_5oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShirakikuRoastedBlackSesameSeed8.5oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shopping_cart_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuntoryBOSSCoffee_ColdBlackCoffee8oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuntoryBOSSCoffee-ColdBlackCoffee8oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SuntoryBOSSCoffee_ColdBlackCoffee8oz_front_540x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SuntoryBOSSCoffee-ColdBlackCoffee8oz_front_540x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Super_Q_Golden_Bihon_Front_976c03a8_fe96_4988_9803_bc963bb8f1d8_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Super-Q-Golden-Bihon_Front_976c03a8-fe96-4988-9803-bc963bb8f1d8_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Super_Q_Golden_Bihon_Front_976c03a8_fe96_4988_9803_bc963bb8f1d8_540x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Super-Q-Golden-Bihon_Front_976c03a8-fe96-4988-9803-bc963bb8f1d8_540x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UFCBananaKetchupHot19oz_FRONT_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UFCBananaKetchupHot19oz_FRONT_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhiteKingHotcakeMix_CreamyClassic14_1oz_front_540x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteKingHotcakeMix-CreamyClassic14.1oz_front_540x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
